- name: Set default variables
  ansible.builtin.set_fact:
    sn_notification_type: googlechat
    sn_systemd_user_final: "{{ sn_systemd_user }}"
    sn_execstart: "{{ systemd_script_target }}/{{ sn_script_name_googlechat }} -s %i -u ${{ sn_googlechat_url_env }} -f"
- name: Creates directory for environment files
  ansible.builtin.file:
    path: "{{ environmentfile_target_dir }}"
    state: directory
    mode: "{{ sn_systemd_script_mode }}"
- name: Set environment file
  ansible.builtin.template:
    src: "{{ sn_environment_file }}.j2"
    dest: "{{ environmentfile_target_dir }}/{{ sn_environment_file }}"
    owner: "{{ sn_systemd_user_final }}"
    group: "{{ sn_systemd_group }}"
    mode: "{{ sn_systemd_script_mode }}"
- name: Install googlechat notifier script
  ansible.builtin.template:
    src: "{{ sn_script_name_googlechat }}.j2"
    dest: "{{ systemd_script_target }}/{{ sn_script_name_googlechat }}"
    owner: "{{ sn_systemd_user_final }}"
    group: "{{ sn_systemd_group }}"
    mode: "{{ sn_systemd_script_mode }}"
- name: Install systemd service for googlechat notifier
  ansible.builtin.template:
    src: "{{ sn_systemd_service_file }}"
    mode: "{{ sn_systemd_service_mode }}"
    dest: "{{ systemd_target_dir }}/{{ sn_service_name_googlechat }}.service"
  register: sn_service_file_changed
- name: Reload systemd unit if args were changed.
  ansible.builtin.systemd:
    daemon_reload: true
