- name: Set default variables
  set_fact:
    sn_notification_type: mail
    sn_systemd_user_final: "{{ sn_systemd_user }}"
    sn_execstart: "{{ systemd_script_target }}/{{ sn_script_name_mail }} -s %i"
- name: Install mail notifier script
  template:
    src: "{{ sn_script_name_mail }}.j2"
    dest: "{{ systemd_script_target }}/{{ sn_script_name_mail }}"
    owner: "{{ sn_systemd_user_final }}"
    group: "{{ sn_systemd_group }}"
    mode: "{{ systemd_script_mode }}"
- name: Install systemd service for mail notifier
  template:
    src: "{{ sn_systemd_service_file }}"
    dest: "{{ systemd_target_dir }}/{{ sn_service_name_mail }}.service"
  register: sn_service_file_changed
- name: Reload systemd unit if args were changed.
  ansible.builtin.systemd:
    daemon_reload: true