- name: Set default variables
  set_fact:
    sn_notification_type: mail
    sn_execstart: "{{ systemd_script_target }}/{{ sn_script_name_mail }} -s %i"
- name: Set variables in case username is set
  set_fact:
    sn_execstart: "{{ systemd_script_target }}/{{ sn_script_name_mail }} -s %i -u {{ sn_username }}"
  when: sn_username is defined
- name: Install mail notifier script
  template:
    src: "{{ sn_script_name_mail }}.j2"
    dest: "{{ systemd_script_target }}/{{ sn_script_name_mail }}"
    owner: "{{ systemd_script_user }}"
    group: "{{ sn_systemd_group }}"
    mode: "{{ systemd_script_mode }}"
- name: Install systemd service for mail notifier
  template:
    src: "{{ sn_systemd_service_file }}"
    dest: "{{ systemd_target_dir }}/{{ sn_service_name_mail }}@.service"
  register: sn_service_file_changed
- name: Reload systemd unit if args were changed.
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    name: "{{ sn_service_name_mail }}"
- name: Enable systemd service for mail notifier
  ansible.builtin.systemd:
    name: "{{ sn_service_name_mail }}@.service"
    state: started
    enabled: yes