- name: Set default variables
  set_fact:
    sn_notification_type: desktop
    sn_execstart: "{{ systemd_script_target }}/{{ sn_script_name_desktop }} -s %i"
- name: Set variables in case username is set
  set_fact:
    sn_execstart: "{{ systemd_script_target }}/{{ sn_script_name_desktop }} -s %i -u {{ sn_username }}"
  when: sn_username is defined
- name: Install desktop notifier script
  template:
    src: "{{ sn_script_name_desktop }}.j2"
    dest: "{{ systemd_script_target }}/{{ sn_script_name_desktop }}"
    owner: "{{ systemd_script_user }}"
    group: "{{ sn_systemd_group }}"
    mode: "{{ systemd_script_mode }}"
- name: Install systemd service for desktop notifier
  template:
    src: "{{ sn_systemd_service_file }}"
    dest: "{{ systemd_target_dir }}/{{ sn_service_name_desktop }}@.service"
  register: sn_service_file_changed
- name: Reload systemd unit if args were changed.
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    name: "{{ sn_service_name_desktop }}"