---
# tasks file for papanito.systemd-notification
- name: Install systemd service for desktop notifications
  ansible.builtin.import_tasks: install-service-desktop-notify.yml
  become: true
  when: sn_install_desktop_notifier_service
- name: Remove systemd service for desktop notifications
  ansible.builtin.import_tasks: remove-service-desktop-notify.yml
  become: true
  when: not sn_install_desktop_notifier_service
- name: Install systemd service for googlechat notifications
  ansible.builtin.import_tasks: install-service-googlechat-notify.yml
  become: true
  when: sn_install_googlechat_notifier_service
- name: Remove systemd service for googlechat notifications
  ansible.builtin.import_tasks: remove-service-googlechat-notify.yml
  become: true
  when: not sn_install_googlechat_notifier_service
- name: Install systemd service for mail notifications
  ansible.builtin.import_tasks: install-service-mail-notify.yml
  become: true
  when: sn_install_mail_notifier_service
- name: Remove systemd service for mail notifications
  ansible.builtin.import_tasks: remove-service-mail-notify.yml
  become: true
  when: not sn_install_mail_notifier_service
